version: 2
updates:
  - package-ecosystem: composer
    directory: "/"
    schedule:
      interval: "daily"
      time: "00:00"
      timezone: "UTC"
    reviewers:
      - Shopify/core-build-learn
    labels:
      - "Composer upgrades"
    open-pull-requests-limit: 100
    registries: '*'

  - directory: /
    open-pull-requests-limit: 5
    package-ecosystem: "github-actions"
    reviewers:
      - "TUDOCK/devops"
    schedule:
      interval: daily
      timezone: "Europe/Berlin"
